# Generated by Django 3.1.6 on 2021-02-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlist',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
