# Generated by Django 3.1.6 on 2021-02-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_itemlist_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlist',
            name='description',
            field=models.TextField(default="This is a test text field lanfkndf falkfnkndl dflkfnnfkla fakfafnlalkbjbsgajlbs'lf j jsabg'l dsl  dgsls dl sa;lg"),
            preserve_default=False,
        ),
    ]
