# Generated by Django 3.1.6 on 2021-02-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210217_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemlist',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
